### ISSUE TITLE
SOAP1.1 and 1.2 Content-Type header

### ISSUE THREAD

**Issue by mohdhallal** [pierre-vigier/XML-Compile-SOAP-Daemon-Dancer2#3]
Hello,

in https://github.com/pierre-vigier/XML-Compile-SOAP-Daemon-Dancer2/blob/master/lib/XML/Compile/SOAP/Daemon/Dancer2/Handler.pm#L87

there needs to be a way to write the correct content-type header value depending if the server is working in SOAP 1.1 or 1.2

SOAP 1.1 content-type header: text/xml; charset="utf-8"
SOAP 1.2 content-type header: application/soap+xml; charset=utf-8

Cheers!

**Comment by pierre-vigier** [comment]
Thanks for the help, released
